Lang.prototype.pack.es = {
	"token": {
		"Back":"Atrás",
	"About":"Info",
	"pins":"pines",
	"health folders":"carpetas",
	"Medical Validation":"Validación Médica",
	"International Classification":"Clasificación Internacional",
	"Personal Backup":"Copia de Seguridad",
	"Storage":"Almacenamiento",
	"Account Configuration":"Configuración Cuenta",
	"Disconnect":"Desconectar",
	"Check Connection":"Comprobar Conexión",
	"Disconnect2":"Desconectar2",
	"User":"Usuario",
	"Capture":"Capturar",
	"eMap":"eMapa",
	"User Account Configuration":"Configuración de la Cuenta",
	"Username":"Nombre",
	"Date Birth":"F. Nacim.",
	"Gender":"Género",
	"Female":"Femenino",
	"Male":"Masculino",
	"Language":"Idioma",
	"English":"Inglés",
	"Spanish":"Español",
	"French":"Francés",
	"Save":"Guardar",
	"Get Report from Library":"Cargar Informe de la Biblioteca",
	"Scan Report with Camera":"Escanear Informe con la Cámara",	
	"Capture":"Escanear",
	"Library":"Biblioteca",	
	"List":"Listado",
	"Map":"Mapa",	
	"Send to my Doctor":"Enviar a mi Médico",
	"Page height":"Alto de pagina",	
	"Wrong Username or Password":"Usuario o passsword erróneo",
	"You must fill all fields":"Debe rellenar todos los campos",
	"User already exists. Please try again.":"El Usuario ya existe. Por favor intente de nuevo",
	"You must read and accept Terms & Conditions to create an account.":"Debe leer y aceptar los Términos y Condiciones.",
	"UserName must be at least 6 characters long":"El nombre de usuario debe contener al menos 6 caracteres",
	"get picture failed":"Falló la captura de imagen",
	"Username":"Usuario",
	"Sign In":"Validar",
	"About":"Acerca de",
	"Forgot Password":"Contraseña Olvidada",
	"Create New User":"Crear Nuevo Usuario",
	"Password":"Contraseña",
	"Agree to the terms:":"Términos y Condiciones:",
	"I agree":"Estoy de acuerdo",
	"Create User":"Crear Usuario",
	"Terms & Conditions":"Términos y Condiciones",
	"Verify Address":"Verificar correo",
	"Reports":"Informes",
	"My Health Map":"Mi Mapa de Salud",
	"Send to my Doctor":"Enviar a mi Médico",
	"DropBox Configuration":"Configuración de Dropbox",
	}
};